### ISSUE TITLE
Frame Overide Not Working

### ISSUE THREAD

**Issue by marlvernchimbwanda** [gstavrinos/odom_to_tf_ros2#2]
Hello so i am trying to setup a TF between odom --> robot_base_footprint and when I change the frame IDs its not overriding them and it  uses the default  ![image](https://github.com/user-attachments/assets/647e2028-6f8c-46e2-85ae-dc60bd606079) . Here is my terminal 
![image](https://github.com/user-attachments/assets/fc8a777a-011d-4864-ae85-ade490d98566)
Maybe I'm missing something, can you please review it for me.

**Comment by marlvernchimbwanda** [comment]
I see where i was getting wrong I have to put the frames in the cpp file as well I was just updating the taml only

**Comment by gstavrinos** [comment]
Dear @marlvernchimbwanda,

I saw your issue and got motivated to add a launch file to help future users easily configure the node. Check #4. In general, you should not have to compile nodes to change parameters. In order to use the yaml configuration files, you need launch files to load the parameters.
